version: '3'
services:
  api:
    build: ./api
    links:
      - db
    ports:
      - '8080:8080'
    volumes:
      - ./api:/api
    environment:
      JAR_TARGET: api-0.0.1-SNAPSHOT.jar
  db:
    build: ./mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: rootpassword
